### PR TITLE
Including java wrapper in default build

### PR DESCRIPTION
**Pull request by d-cameron**
Added basic documentation for the java wrapper, merged the java-specific Makefile into the main one.

### CODE REVIEW

**Comment by d-cameron** [comment]
If java is not installed on the target system, `make all` will now fail. I've added some readme text around getting the command line ssw_test building in such a case but if you think it's a problem, I can change the Makefile so the default rule is not `all`.

**Comment by mengyao** [comment]
Dear Daniel,

Thanks a lot.

Yes, I think it will be better, if you can change the default rule of Makefile Not all. 

Yours,

Mengyao

**Comment by d-cameron** [comment]
A default make goal that only compiles the C/C++ code has been added as well as an the java wrapper an explicit `make java` goal. `make all` will still make everything but it's no longer the default.

**Comment by mengyao** [comment]
Thanks a lot.

**Pull request merged**
